### PR TITLE
fix: use newer quart API, update docs

### LINKED ISSUE #2: support 3.8
Is it possible to support 3.8 ? Flask is >=3.6

### PR DESCRIPTION
**Pull request by binary1230**
- fixes https://github.com/go-build-it/quart-github-webhook/issues/2 credit to @NargiT for the fix
- update the example in the README to provide the required "push" param

Tested locally, seems to work ok, haven't run any serious tests or anything on it.

### CODE REVIEW

**Comment by binary1230** [comment]
note: unit tests weren't working upstream either, so this PR doesn't newly break them. not it : )

**Comment by AstraLuma** [comment]
1. I am going to ask you fix the flake8 errors
2. Your branch looks like it caused at least one of the test failures. Please fix that test.

**Comment by NargiT** [comment]
IHO this project is dead. I already switch to fastapi most of my webapps and handle myself github events.

**Comment by AstraLuma** [comment]
I honestly didn't know anyone but me was using it

**Comment by NargiT** [comment]
no worries @AstraLuma it's not easy to keep up to date libs. It help us a lot, and now we have more knowledge on github api we can drop this lib and use our own implementation.

**Pull request merged**
